### ISSUE TITLE
AutoEye Code Review [Riyadh]

### ISSUE THREAD

**Issue by Riyadh-kh** [AV-Lab/AutoEye#14]
Tasks for @mohddotio.

Write documentation to:
- [ ] 1- Install NodeJS
- [ ] 2- NPM Install
- [ ] 3- Authentication Codes (GraphQL) - creating users, etc.
- [ ] 4- .ENV file
- [ ] 5- Starting scripts (npm run *)
- [ ] 6- Graphql Documentation
- [ ] 7- Postman & MQTT
- [ ] 8- ROS Node
- [ ] 9- User Guide / Manual

**Comment by mohddotio** [comment]
@Murdism
