### ISSUE TITLE
Create Roles CRUD 

### ISSUE THREAD

**Issue by mohdbk** [AV-Lab/AutoEye#7]
### Description
This enhancement focuses on implementing CRUD functionality for roles within AutoEye's authorization system. The ability to manage roles dynamically is essential for administrators to fine-tune access control and permissions within the application effectively.

### Tasks
- Develop back-end endpoints to support CRUD operations for roles, including creation, retrieval, updating, and deletion.
- Design and implement front-end interfaces to enable administrators to manage roles efficiently.
- Ensure proper validation and error handling mechanisms are in place to maintain data integrity.

### Additional Information
- Dynamic role management enhances the flexibility and scalability of AutoEye's authorization system, allowing administrators to adapt access control policies as needed.
- Roles CRUD functionality lays the foundation for more granular permission management within the application.

### Acceptance Criteria
- Back-end endpoints for roles CRUD operations are implemented and thoroughly tested to ensure reliability and security.
- Front-end interfaces enable administrators to create, view, update, and delete roles with ease.
- Changes to roles are reflected accurately in the system, and appropriate access controls are enforced based on role permissions.

**Comment by Syed-Abbas-Hussain** [comment]
Closed with PR #16
